version: "3"
services:
  counter-app:
    image: 127.0.0.1:5000/swarm-app
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
    deploy:
      mode: replicated
      replicas: 4

