version: "3"
services:
  flask_app:
    container_name: flask_app
    image: flask_app
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresql_db:5432/postgres
    depends_on:
      - postgresql_db
  postgresql_db:
    container_name: postgresql_db
    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata: {}